version: "3.3"

services:
  dp-upload-service:
    build:
        context: ../../../dp-upload-service
        dockerfile: Dockerfile-local
    command:
        - go
        - test
        - -cover
        - -coverpkg=github.com/ONSdigital/dp-upload-service/...
        - -component
    volumes:
      - ../../:/dp-upload-service
    ports:
      - "25100:25100"
    depends_on:
      - localstack
      - vault
    environment:
      BIND_ADDR: ":25100"
      AWS_REGION: "eu-west-2" # http://localstack:4572
      UPLOAD_BUCKET_NAME: "deprecated"
      STATIC_FILES_ENCRYPTED_BUCKET_NAME: "testing"
      ENCRYPTION_DISABLED: "false"
      GRACEFUL_SHUTDOWN_TIMEOUT: "5s"
      HEALTHCHECK_INTERVAL: "5s"
      HEALTHCHECK_CRITICAL_TIMEOUT: "5s"
      LOCALSTACK_HOST: "http://localstack:4566"
      VAULT_TOKEN: "0000-0000-0000-0000"
      VAULT_ADDR: "http://vault:8200"
      VAULT_PATH: "secret/shared/psk"
