// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock_files

import (
	"context"
	filesAPITypes "github.com/ONSdigital/dp-files-api/files"
	filesSDK "github.com/ONSdigital/dp-files-api/sdk"
	"github.com/ONSdigital/dp-upload-service/files"
	"sync"
)

// Ensure, that FilesClienterMock does implement files.FilesClienter.
// If this is not the case, regenerate this file with moq.
var _ files.FilesClienter = &FilesClienterMock{}

// FilesClienterMock is a mock implementation of files.FilesClienter.
//
//	func TestSomethingThatUsesFilesClienter(t *testing.T) {
//
//		// make and configure a mocked files.FilesClienter
//		mockedFilesClienter := &FilesClienterMock{
//			GetFileFunc: func(ctx context.Context, path string, headers filesSDK.Headers) (*filesAPITypes.StoredRegisteredMetaData, error) {
//				panic("mock out the GetFile method")
//			},
//			MarkFilePublishedFunc: func(ctx context.Context, path string, headers filesSDK.Headers) error {
//				panic("mock out the MarkFilePublished method")
//			},
//			MarkFileUploadedFunc: func(ctx context.Context, path string, etag string, headers filesSDK.Headers) error {
//				panic("mock out the MarkFileUploaded method")
//			},
//			RegisterFileFunc: func(ctx context.Context, metadata filesAPITypes.StoredRegisteredMetaData, headers filesSDK.Headers) error {
//				panic("mock out the RegisterFile method")
//			},
//		}
//
//		// use mockedFilesClienter in code that requires files.FilesClienter
//		// and then make assertions.
//
//	}
type FilesClienterMock struct {
	// GetFileFunc mocks the GetFile method.
	GetFileFunc func(ctx context.Context, path string, headers filesSDK.Headers) (*filesAPITypes.StoredRegisteredMetaData, error)

	// MarkFilePublishedFunc mocks the MarkFilePublished method.
	MarkFilePublishedFunc func(ctx context.Context, path string, headers filesSDK.Headers) error

	// MarkFileUploadedFunc mocks the MarkFileUploaded method.
	MarkFileUploadedFunc func(ctx context.Context, path string, etag string, headers filesSDK.Headers) error

	// RegisterFileFunc mocks the RegisterFile method.
	RegisterFileFunc func(ctx context.Context, metadata filesAPITypes.StoredRegisteredMetaData, headers filesSDK.Headers) error

	// calls tracks calls to the methods.
	calls struct {
		// GetFile holds details about calls to the GetFile method.
		GetFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Headers is the headers argument value.
			Headers filesSDK.Headers
		}
		// MarkFilePublished holds details about calls to the MarkFilePublished method.
		MarkFilePublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Headers is the headers argument value.
			Headers filesSDK.Headers
		}
		// MarkFileUploaded holds details about calls to the MarkFileUploaded method.
		MarkFileUploaded []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Etag is the etag argument value.
			Etag string
			// Headers is the headers argument value.
			Headers filesSDK.Headers
		}
		// RegisterFile holds details about calls to the RegisterFile method.
		RegisterFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Metadata is the metadata argument value.
			Metadata filesAPITypes.StoredRegisteredMetaData
			// Headers is the headers argument value.
			Headers filesSDK.Headers
		}
	}
	lockGetFile           sync.RWMutex
	lockMarkFilePublished sync.RWMutex
	lockMarkFileUploaded  sync.RWMutex
	lockRegisterFile      sync.RWMutex
}

// GetFile calls GetFileFunc.
func (mock *FilesClienterMock) GetFile(ctx context.Context, path string, headers filesSDK.Headers) (*filesAPITypes.StoredRegisteredMetaData, error) {
	if mock.GetFileFunc == nil {
		panic("FilesClienterMock.GetFileFunc: method is nil but FilesClienter.GetFile was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Path    string
		Headers filesSDK.Headers
	}{
		Ctx:     ctx,
		Path:    path,
		Headers: headers,
	}
	mock.lockGetFile.Lock()
	mock.calls.GetFile = append(mock.calls.GetFile, callInfo)
	mock.lockGetFile.Unlock()
	return mock.GetFileFunc(ctx, path, headers)
}

// GetFileCalls gets all the calls that were made to GetFile.
// Check the length with:
//
//	len(mockedFilesClienter.GetFileCalls())
func (mock *FilesClienterMock) GetFileCalls() []struct {
	Ctx     context.Context
	Path    string
	Headers filesSDK.Headers
} {
	var calls []struct {
		Ctx     context.Context
		Path    string
		Headers filesSDK.Headers
	}
	mock.lockGetFile.RLock()
	calls = mock.calls.GetFile
	mock.lockGetFile.RUnlock()
	return calls
}

// MarkFilePublished calls MarkFilePublishedFunc.
func (mock *FilesClienterMock) MarkFilePublished(ctx context.Context, path string, headers filesSDK.Headers) error {
	if mock.MarkFilePublishedFunc == nil {
		panic("FilesClienterMock.MarkFilePublishedFunc: method is nil but FilesClienter.MarkFilePublished was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Path    string
		Headers filesSDK.Headers
	}{
		Ctx:     ctx,
		Path:    path,
		Headers: headers,
	}
	mock.lockMarkFilePublished.Lock()
	mock.calls.MarkFilePublished = append(mock.calls.MarkFilePublished, callInfo)
	mock.lockMarkFilePublished.Unlock()
	return mock.MarkFilePublishedFunc(ctx, path, headers)
}

// MarkFilePublishedCalls gets all the calls that were made to MarkFilePublished.
// Check the length with:
//
//	len(mockedFilesClienter.MarkFilePublishedCalls())
func (mock *FilesClienterMock) MarkFilePublishedCalls() []struct {
	Ctx     context.Context
	Path    string
	Headers filesSDK.Headers
} {
	var calls []struct {
		Ctx     context.Context
		Path    string
		Headers filesSDK.Headers
	}
	mock.lockMarkFilePublished.RLock()
	calls = mock.calls.MarkFilePublished
	mock.lockMarkFilePublished.RUnlock()
	return calls
}

// MarkFileUploaded calls MarkFileUploadedFunc.
func (mock *FilesClienterMock) MarkFileUploaded(ctx context.Context, path string, etag string, headers filesSDK.Headers) error {
	if mock.MarkFileUploadedFunc == nil {
		panic("FilesClienterMock.MarkFileUploadedFunc: method is nil but FilesClienter.MarkFileUploaded was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Path    string
		Etag    string
		Headers filesSDK.Headers
	}{
		Ctx:     ctx,
		Path:    path,
		Etag:    etag,
		Headers: headers,
	}
	mock.lockMarkFileUploaded.Lock()
	mock.calls.MarkFileUploaded = append(mock.calls.MarkFileUploaded, callInfo)
	mock.lockMarkFileUploaded.Unlock()
	return mock.MarkFileUploadedFunc(ctx, path, etag, headers)
}

// MarkFileUploadedCalls gets all the calls that were made to MarkFileUploaded.
// Check the length with:
//
//	len(mockedFilesClienter.MarkFileUploadedCalls())
func (mock *FilesClienterMock) MarkFileUploadedCalls() []struct {
	Ctx     context.Context
	Path    string
	Etag    string
	Headers filesSDK.Headers
} {
	var calls []struct {
		Ctx     context.Context
		Path    string
		Etag    string
		Headers filesSDK.Headers
	}
	mock.lockMarkFileUploaded.RLock()
	calls = mock.calls.MarkFileUploaded
	mock.lockMarkFileUploaded.RUnlock()
	return calls
}

// RegisterFile calls RegisterFileFunc.
func (mock *FilesClienterMock) RegisterFile(ctx context.Context, metadata filesAPITypes.StoredRegisteredMetaData, headers filesSDK.Headers) error {
	if mock.RegisterFileFunc == nil {
		panic("FilesClienterMock.RegisterFileFunc: method is nil but FilesClienter.RegisterFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Metadata filesAPITypes.StoredRegisteredMetaData
		Headers  filesSDK.Headers
	}{
		Ctx:      ctx,
		Metadata: metadata,
		Headers:  headers,
	}
	mock.lockRegisterFile.Lock()
	mock.calls.RegisterFile = append(mock.calls.RegisterFile, callInfo)
	mock.lockRegisterFile.Unlock()
	return mock.RegisterFileFunc(ctx, metadata, headers)
}

// RegisterFileCalls gets all the calls that were made to RegisterFile.
// Check the length with:
//
//	len(mockedFilesClienter.RegisterFileCalls())
func (mock *FilesClienterMock) RegisterFileCalls() []struct {
	Ctx      context.Context
	Metadata filesAPITypes.StoredRegisteredMetaData
	Headers  filesSDK.Headers
} {
	var calls []struct {
		Ctx      context.Context
		Metadata filesAPITypes.StoredRegisteredMetaData
		Headers  filesSDK.Headers
	}
	mock.lockRegisterFile.RLock()
	calls = mock.calls.RegisterFile
	mock.lockRegisterFile.RUnlock()
	return calls
}
