ignore:
  - id: GO-2026-4340
    reason: "Resolved in Go 1.24.12; cannot upgrade due to mongo-in-memory incompatibility which requires Go 1.24.6-bullseye."
  - id: GO-2026-4341
    reason: "Resolved in Go 1.24.12; cannot upgrade due to mongo-in-memory incompatibility which requires Go 1.24.6-bullseye."