version: "3.3"

services:
  upload-service:
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
      - "25100:25100"
    environment:
      BIND_ADDR: 'localhost:25100'
      AWS_REGION: 'eu-west-2' # http://localstack:4572
      UPLOAD_BUCKET_NAME: 'deprecated'
      STATIC_FILES_ENCRYPTED_BUCKET_NAME: 'testing'
      ENCRYPTION_DISABLED: 'false'
      GRACEFUL_SHUTDOWN_TIMEOUT: '5s'
      HEALTHCHECK_INTERVAL: '5s'
      HEALTHCHECK_CRITICAL_TIMEOUT: '5s'
      VAULT_TOKEN: '0000-0000-0000-0000'
      VAULT_ADDR: 'http://vault:8200'
      VAULT_PATH: 'secret/shared/psk'
    volumes:
      - ./:/service
