FROM golang:1.22-bullseye as build

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

RUN GOBIN=/bin go install github.com/cespare/reflex@latest

# Map between the working directories of dev and live 
RUN ln -s /go /dp-upload-service
WORKDIR /dp-upload-service
