version: "3.3"

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
    volumes:
      - ./aws:/etc/localstack/init/ready.d/
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
