// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock_aws

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	s3client "github.com/ONSdigital/dp-s3/v2"
	"github.com/ONSdigital/dp-upload-service/aws"
	"github.com/aws/aws-sdk-go/service/s3"
	"sync"
)

// Ensure, that S3ClienterMock does implement aws.S3Clienter.
// If this is not the case, regenerate this file with moq.
var _ aws.S3Clienter = &S3ClienterMock{}

// S3ClienterMock is a mock implementation of aws.S3Clienter.
//
//	func TestSomethingThatUsesS3Clienter(t *testing.T) {
//
//		// make and configure a mocked aws.S3Clienter
//		mockedS3Clienter := &S3ClienterMock{
//			CheckPartUploadedFunc: func(ctx context.Context, req *s3client.UploadPartRequest) (bool, error) {
//				panic("mock out the CheckPartUploaded method")
//			},
//			CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			HeadFunc: func(key string) (*s3.HeadObjectOutput, error) {
//				panic("mock out the Head method")
//			},
//			UploadPartFunc: func(ctx context.Context, req *s3client.UploadPartRequest, payload []byte) (s3client.MultipartUploadResponse, error) {
//				panic("mock out the UploadPart method")
//			},
//		}
//
//		// use mockedS3Clienter in code that requires aws.S3Clienter
//		// and then make assertions.
//
//	}
type S3ClienterMock struct {
	// CheckPartUploadedFunc mocks the CheckPartUploaded method.
	CheckPartUploadedFunc func(ctx context.Context, req *s3client.UploadPartRequest) (bool, error)

	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// HeadFunc mocks the Head method.
	HeadFunc func(key string) (*s3.HeadObjectOutput, error)

	// UploadPartFunc mocks the UploadPart method.
	UploadPartFunc func(ctx context.Context, req *s3client.UploadPartRequest, payload []byte) (s3client.MultipartUploadResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckPartUploaded holds details about calls to the CheckPartUploaded method.
		CheckPartUploaded []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *s3client.UploadPartRequest
		}
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// Head holds details about calls to the Head method.
		Head []struct {
			// Key is the key argument value.
			Key string
		}
		// UploadPart holds details about calls to the UploadPart method.
		UploadPart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *s3client.UploadPartRequest
			// Payload is the payload argument value.
			Payload []byte
		}
	}
	lockCheckPartUploaded sync.RWMutex
	lockChecker           sync.RWMutex
	lockHead              sync.RWMutex
	lockUploadPart        sync.RWMutex
}

// CheckPartUploaded calls CheckPartUploadedFunc.
func (mock *S3ClienterMock) CheckPartUploaded(ctx context.Context, req *s3client.UploadPartRequest) (bool, error) {
	if mock.CheckPartUploadedFunc == nil {
		panic("S3ClienterMock.CheckPartUploadedFunc: method is nil but S3Clienter.CheckPartUploaded was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *s3client.UploadPartRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCheckPartUploaded.Lock()
	mock.calls.CheckPartUploaded = append(mock.calls.CheckPartUploaded, callInfo)
	mock.lockCheckPartUploaded.Unlock()
	return mock.CheckPartUploadedFunc(ctx, req)
}

// CheckPartUploadedCalls gets all the calls that were made to CheckPartUploaded.
// Check the length with:
//
//	len(mockedS3Clienter.CheckPartUploadedCalls())
func (mock *S3ClienterMock) CheckPartUploadedCalls() []struct {
	Ctx context.Context
	Req *s3client.UploadPartRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *s3client.UploadPartRequest
	}
	mock.lockCheckPartUploaded.RLock()
	calls = mock.calls.CheckPartUploaded
	mock.lockCheckPartUploaded.RUnlock()
	return calls
}

// Checker calls CheckerFunc.
func (mock *S3ClienterMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("S3ClienterMock.CheckerFunc: method is nil but S3Clienter.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedS3Clienter.CheckerCalls())
func (mock *S3ClienterMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Head calls HeadFunc.
func (mock *S3ClienterMock) Head(key string) (*s3.HeadObjectOutput, error) {
	if mock.HeadFunc == nil {
		panic("S3ClienterMock.HeadFunc: method is nil but S3Clienter.Head was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockHead.Lock()
	mock.calls.Head = append(mock.calls.Head, callInfo)
	mock.lockHead.Unlock()
	return mock.HeadFunc(key)
}

// HeadCalls gets all the calls that were made to Head.
// Check the length with:
//
//	len(mockedS3Clienter.HeadCalls())
func (mock *S3ClienterMock) HeadCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockHead.RLock()
	calls = mock.calls.Head
	mock.lockHead.RUnlock()
	return calls
}

// UploadPart calls UploadPartFunc.
func (mock *S3ClienterMock) UploadPart(ctx context.Context, req *s3client.UploadPartRequest, payload []byte) (s3client.MultipartUploadResponse, error) {
	if mock.UploadPartFunc == nil {
		panic("S3ClienterMock.UploadPartFunc: method is nil but S3Clienter.UploadPart was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Req     *s3client.UploadPartRequest
		Payload []byte
	}{
		Ctx:     ctx,
		Req:     req,
		Payload: payload,
	}
	mock.lockUploadPart.Lock()
	mock.calls.UploadPart = append(mock.calls.UploadPart, callInfo)
	mock.lockUploadPart.Unlock()
	return mock.UploadPartFunc(ctx, req, payload)
}

// UploadPartCalls gets all the calls that were made to UploadPart.
// Check the length with:
//
//	len(mockedS3Clienter.UploadPartCalls())
func (mock *S3ClienterMock) UploadPartCalls() []struct {
	Ctx     context.Context
	Req     *s3client.UploadPartRequest
	Payload []byte
} {
	var calls []struct {
		Ctx     context.Context
		Req     *s3client.UploadPartRequest
		Payload []byte
	}
	mock.lockUploadPart.RLock()
	calls = mock.calls.UploadPart
	mock.lockUploadPart.RUnlock()
	return calls
}
